import type { Restaurant, MenuItem, Table } from './types'

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Le Loup Imperial',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    rating: 5.0,
    cuisines: ['Italian'],
    tags: ['Pet-friendly'],
    isOpen: true,
    hours: '9:00AM - 8:00PM',
    address: "Claren's St., 123/9",
    description: 'An elegant Italian restaurant with a cozy atmosphere and authentic recipes.',
  },
  {
    id: '2',
    name: 'The Island',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop',
    rating: 3.6,
    cuisines: ['French'],
    tags: ['Vegetarian'],
    isOpen: false,
    hours: '10:00AM - 11:00PM',
    address: "Claren's St., 128",
    description: 'A French bistro offering exquisite vegetarian options.',
  },
  {
    id: '3',
    name: 'Sakura Garden',
    image: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=400&h=300&fit=crop',
    rating: 4.8,
    cuisines: ['Japanese'],
    tags: ['Sushi', 'Omakase'],
    isOpen: true,
    hours: '11:00AM - 10:00PM',
    address: 'Oak Avenue, 45',
    description: 'Authentic Japanese cuisine with fresh sushi and traditional dishes.',
  },
  {
    id: '4',
    name: 'Bella Napoli',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400&h=300&fit=crop',
    rating: 4.5,
    cuisines: ['Italian'],
    tags: ['Family-friendly', 'Pizza'],
    isOpen: true,
    hours: '12:00PM - 11:00PM',
    address: 'Main Street, 78',
    description: 'Traditional Neapolitan pizza made with imported ingredients.',
  },
  {
    id: '5',
    name: 'Bodhi Vegan Living',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop',
    rating: 9.5,
    cuisines: ['Chinese'],
    tags: ['Vegan', 'Vegetarian'],
    isOpen: true,
    hours: '11:00AM - 10:00PM',
    address: 'Lange Reihe 93, Hamburg',
    description: 'Award-winning vegan Asian cuisine with creative plant-based dishes.',
  },
  {
    id: '6',
    name: 'Fischereihafen Restaurant',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    rating: 4.7,
    cuisines: ['German'],
    tags: ['Seafood'],
    isOpen: true,
    hours: '11:30AM - 11:00PM',
    address: 'Grosse Elbstrasse 143',
    description: 'Premium seafood restaurant overlooking the Elbe river.',
  },
  {
    id: '7',
    name: 'Trattoria da Enzo',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
    rating: 4.4,
    cuisines: ['Italian'],
    tags: ['Pet-friendly'],
    isOpen: false,
    hours: '5:00PM - 10:30PM',
    address: 'Schulterblatt 73',
    description: 'Cozy Italian trattoria serving homemade pasta and regional wines.',
  },
  {
    id: '8',
    name: 'Golden Dragon',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&h=300&fit=crop',
    rating: 4.2,
    cuisines: ['Chinese'],
    tags: ['Family-friendly'],
    isOpen: true,
    hours: '11:00AM - 11:30PM',
    address: 'Steindamm 54',
    description: 'Authentic Cantonese and Sichuan cuisine with dim sum brunch.',
  },
]

export const menuItems: MenuItem[] = [
  // Starters
  {
    id: 'm1',
    name: 'Bruschetta Classica',
    description: 'Grilled bread rubbed with garlic, topped with tomatoes, basil, and olive oil',
    price: 8.5,
    category: 'Starters',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=200&h=150&fit=crop',
  },
  {
    id: 'm2',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze',
    price: 12.0,
    category: 'Starters',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=200&h=150&fit=crop',
  },
  {
    id: 'm3',
    name: 'Soup of the Day',
    description: 'Ask your server for today\'s selection',
    price: 7.0,
    category: 'Starters',
    isAvailable: true,
  },
  // Main Courses
  {
    id: 'm4',
    name: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with eggs, pecorino cheese, guanciale, and black pepper',
    price: 18.5,
    category: 'Main Courses',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=200&h=150&fit=crop',
  },
  {
    id: 'm5',
    name: 'Risotto ai Funghi',
    description: 'Creamy arborio rice with wild mushrooms and parmesan',
    price: 22.0,
    category: 'Main Courses',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=200&h=150&fit=crop',
  },
  {
    id: 'm6',
    name: 'Osso Buco',
    description: 'Braised veal shanks with vegetables, white wine, and gremolata',
    price: 32.0,
    category: 'Main Courses',
    isAvailable: false,
  },
  {
    id: 'm7',
    name: 'Grilled Sea Bass',
    description: 'Fresh sea bass with lemon, capers, and roasted vegetables',
    price: 28.0,
    category: 'Main Courses',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=200&h=150&fit=crop',
  },
  // Pizzas
  {
    id: 'm8',
    name: 'Margherita',
    description: 'San Marzano tomatoes, fresh mozzarella, basil, olive oil',
    price: 14.0,
    category: 'Pizza',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&h=150&fit=crop',
  },
  {
    id: 'm9',
    name: 'Quattro Formaggi',
    description: 'Mozzarella, gorgonzola, fontina, and parmigiano',
    price: 18.0,
    category: 'Pizza',
    isAvailable: true,
  },
  // Desserts
  {
    id: 'm10',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone',
    price: 9.0,
    category: 'Desserts',
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=200&h=150&fit=crop',
  },
  {
    id: 'm11',
    name: 'Panna Cotta',
    description: 'Silky vanilla cream with berry compote',
    price: 8.0,
    category: 'Desserts',
    isAvailable: true,
  },
  // Drinks
  {
    id: 'm12',
    name: 'Espresso',
    description: 'Double shot of Italian espresso',
    price: 3.5,
    category: 'Drinks',
    isAvailable: true,
  },
  {
    id: 'm13',
    name: 'House Wine',
    description: 'Glass of red or white house wine',
    price: 8.0,
    category: 'Drinks',
    isAvailable: true,
  },
  {
    id: 'm14',
    name: 'San Pellegrino',
    description: 'Sparkling mineral water (500ml)',
    price: 4.0,
    category: 'Drinks',
    isAvailable: true,
  },
]

export const tables: Table[] = [
  // Garden section
  { id: 't1', number: 1, section: 'Garden', capacity: 2, shape: 'round', isAvailable: true },
  { id: 't2', number: 2, section: 'Garden', capacity: 4, shape: 'rectangular', isAvailable: true },
  { id: 't3', number: 3, section: 'Garden', capacity: 6, shape: 'rectangular', isAvailable: false },
  // Fountain section
  { id: 't4', number: 1, section: 'Fountain', capacity: 2, shape: 'round', isAvailable: true },
  { id: 't5', number: 2, section: 'Fountain', capacity: 4, shape: 'rectangular', isAvailable: true },
  { id: 't6', number: 3, section: 'Fountain', capacity: 4, shape: 'square', isAvailable: true },
  { id: 't7', number: 4, section: 'Fountain', capacity: 2, shape: 'round', isAvailable: true },
  { id: 't8', number: 5, section: 'Fountain', capacity: 6, shape: 'rectangular', isAvailable: true },
  { id: 't9', number: 6, section: 'Fountain', capacity: 2, shape: 'round', isAvailable: false },
  // 1st Floor section
  { id: 't10', number: 1, section: '1st Floor', capacity: 8, shape: 'rectangular', isAvailable: true },
  { id: 't11', number: 2, section: '1st Floor', capacity: 4, shape: 'round', isAvailable: true },
  { id: 't12', number: 3, section: '1st Floor', capacity: 6, shape: 'rectangular', isAvailable: true },
]

export const menuCategories = ['Starters', 'Main Courses', 'Pizza', 'Desserts', 'Drinks']
